sonar.organization=arquisoft
sonar.host.url=https://sonarcloud.io
sonar.projectKey=Arquisoft_yovi_en2b
sonar.projectName=yovi_en2b

sonar.sources=webapp/src,users,gamey/src,game/src,interop/src
sonar.tests=webapp/src,users/src/__tests__,gamey/src,game/src/__tests__,interop/src/__tests__
sonar.test.inclusions=**/*.test.tsx,**/*.test.js,**/*.test.ts
sonar.coverage.exclusions=**/src/__tests__/testDatabase.ts,**/src/__tests__/setup.ts
sonar.exclusions=**/src/__tests__/testDatabase.ts
sonar.cpd.exclusions=webapp/src/i18n/*.ts
sonar.javascript.lcov.reportPaths=webapp/coverage/lcov.info,users/coverage/lcov.info,game/coverage/lcov.info,interop/coverage/lcov.info
sonar.rust.lcov.reportPaths=gamey/lcov.info