resolver 127.0.0.11 ipv6=off;

upstream users      { server users:3000; }
upstream gamey      { server gamey:4000; }
upstream prometheus { server prometheus:9090; }
upstream grafana    { server grafana:3000; }

# SPA -> http://localhost
server {
    listen 80;
    server_name localhost;

    # CORS
    add_header "Access-Control-Allow-Origin" "https://api.localhost" always;
    add_header "Access-Control-Allow-Methods" "GET,POST,PUT,DELETE,OPTIONS,PATCH" always;
    add_header "Access-Control-Allow-Headers" "Content-Type,Authorization" always;
    add_header "Access-Control-Allow-Credentials" "true" always;
    

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-store";
    }
}

# API -> http://api.localhost
server {
    listen 80;
    server_name api.localhost;

    # CORS
    add_header "Access-Control-Allow-Origin"  "http://localhost" always;
    add_header "Access-Control-Allow-Methods" "GET,POST,PUT,DELETE,OPTIONS,PATCH" always;
    add_header "Access-Control-Allow-Headers" "Content-Type,Authorization" always;
    add_header "Access-Control-Allow-Credentials" "true" always;

    location /users/ {
        if ($request_method = 'OPTIONS') { return 204; }
        proxy_pass http://users/;
        include /etc/nginx/snippets/proxy-headers.conf;
        proxy_redirect / /users/;
        proxy_redirect http:// /users/;
    }

    location /gamey/ {
        if ($request_method = 'OPTIONS') { return 204; }
        proxy_pass http://gamey/;
        include /etc/nginx/snippets/proxy-headers.conf;
        proxy_redirect / /gamey/;
        proxy_redirect http:// /gamey/; 
    }
}

# Monitoring -> http://monitoring.localhost
server {
    listen 80;
    server_name monitoring.localhost;

    location /prometheus/ {
        proxy_pass http://prometheus/;
        include /etc/nginx/snippets/proxy-headers.conf;
        proxy_redirect / /prometheus/;
        proxy_redirect http:// /prometheus/;
    }

    location /grafana/ {
        proxy_pass http://grafana/;
        include /etc/nginx/snippets/proxy-headers.conf;
        proxy_set_header Upgrade    $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_redirect / /grafana/;
        proxy_redirect http:// /grafana/;
    }
}
